# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e24300e820cfe4d5265158042305cc1dde3a7e0f9604a470bbaa1f8a118d74d14e72624d9de02c226ff4ee7e318a104cf97c4a7959f623db93cce360c20f4e6

test:
  secret_key_base: 9a84282e28e6241bbbd62d57f060c7f8b212cc13f50bfd3ce52234411bb0662324590a0e00c9d50f7b7540e31b958c6b0151cf9abe001029a3ca668eab120032

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
